version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: attendance-mysql
    environment:
      MYSQL_DATABASE: attendance_db
      MYSQL_USER: manthan
      MYSQL_PASSWORD: manthan7698
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: